#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

PROG="/opt/opensoho/opensoho"
ENV_FILE="/etc/opensoho.env"

start_service() {
    . "$ENV_FILE"

    procd_open_instance

    procd_set_param env \
        OPENSOHO_SHARED_SECRET="$OPENSOHO_SHARED_SECRET" 

    procd_set_param command "$PROG" \
        "$OPENSOHO_ADDR":"$OPENSOHO_PORT"

    procd_set_param user opensoho
    procd_set_param group opensoho

    procd_set_param stdout 1
    procd_set_param stderr 1


    procd_set_param respawn 3600 5 5

    procd_close_instance
}
