#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance

    procd_set_param command /opt/tits/true-imap-tunnel -config /opt/tits/S.yaml
    procd_set_param user nobody
    procd_set_param group nogroup

    procd_set_param respawn 3600 5 5

    procd_close_instance
}
